import styles from "@/styles/Home.module.css";
import { signOut, useSession } from "next-auth/react";
import { Inter } from "next/font/google";
import Head from "next/head";
import { useRouter } from "next/router";
const inter = Inter({ subsets: ["latin"] });

export default function Protected() {
  const router = useRouter();
  const { status, data } = useSession();

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div className={styles.description}>
          <h1>Hello {data?.user?.email}</h1>
          <button onClick={() => signOut()}>SignOut</button>
        </div>
      </main>
    </>
  );
}
